baseurl = "https://tillepille.github.io"
DefaultContentLanguage = "en"
title = "tillepille"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  homeTitle = "HelloWorld!"
  subtitle = "Just a guy who knows nothing"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "2nd January 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "Tim Schrumpf"
  website = "tillepille.io"
  email = "tim@tillepille.io"
  github = "tillepille"
  gitlab = "tillepille"
  twitter = "timschrumpf"
  linkedin = "tim-schrumpf-616121183"
  mastodon = "hachyderm.io/@tillepille"
  reddit = "tillepile"

[[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3
[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 3
[[menu.main]]
    name = "Impressum"
    url = "impressum"
    weight = 4
