baseurl = "https://tillepille.github.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "en"
title = "tillepille"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "HelloWorld!" # Set a different text for the header on the home page
  subtitle = "Just a guy who knows nothing"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "2nd January 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Tim Schrumpf"
  website = "tillepille.io"
  email = "tim@tillepille.io"
  github = "tillepille"
  gitlab = "tillepille"
  twitter = "timschrumpf"
  linkedin = "tim-schrumpf-616121183"
  mastodon = "hachyderm.io/@tillepille"
 # facebook = "username"
 # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
 # bitbucket = "username"
 # reddit = "username"
 # xing = "username"
 # stackoverflow = "users/XXXXXXX/username"
 # snapchat = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"

[[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3
[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 3
[[menu.main]]
    name = "Impressum"
    url = "impressum"
    weight = 4

# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2
#
# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1
#
# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2
#
# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3
